package main

import (
	"fmt"
	"os"
	"reflect"
	"strconv"
	"strings"
	"text/template"

	"github.com/hwaf/hwaf/hlib"
)

//type wenv_t map[string]interface{} //FIXME: map[string][]interface{} instead ??

// type hbuild_t struct {
// 	Targets  htargets_t `yaml:"tgts,flow,omitempty"`
// 	HwafCall []string   `yaml:"hwaf-call,flow,omitempty"`
// }

func (r *Renderer) render_wscript() error {
	var err error

	_, err = fmt.Fprintf(
		r.w,
		`## automatically generated by cmt2yml
## do NOT edit

## waf imports
import waflib.Logs as msg

`,
	)
	handle_err(err)

	wscript := &r.pkg

	// generate package header
	const pkg_hdr_tmpl = `
PACKAGE = {
    "name":    "{{.Name}}",
    "authors": {{.Authors | as_pylist}},
{{if .Managers}}    "managers": {{.Managers | as_pylist}},{{end}}
{{if .Version}}    "version":  "{{.Version}}",{{end}}
}

### ---------------------------------------------------------------------------
def pkg_deps(ctx):
    {{. | gen_wscript_pkg_deps}}
    return # pkg_deps
`
	err = w_tmpl(r.w, pkg_hdr_tmpl, wscript.Package)
	handle_err(err)

	// generate options - section
	err = w_tmpl(
		r.w,
		`

### ---------------------------------------------------------------------------
def options(ctx):
    {{range .Tools}}ctx.load("{{.}}")
    {{end}}
    return # options
`,
		wscript.Options,
	)
	handle_err(err)

	// generate configure - section
	err = w_tmpl(
		r.w,
		`

### ---------------------------------------------------------------------------
def configure(ctx):
    {{range .Tools}}ctx.load("{{.}}")
    {{end}}
    {{range .Stmts}}##{{. | gen_wscript_stmts}}
    {{end}}
    return # configure
`,
		wscript.Configure,
	)
	handle_err(err)

	// generate build - section
	err = w_tmpl(
		r.w,
		`

### ---------------------------------------------------------------------------
def build(ctx):
    {{range .Tools}}ctx.load("{{.}}")
    {{end}}
    {{range .Stmts}}##{{. | gen_wscript_stmts}}
    {{end}}
    {{with .Targets}}{{. | gen_wscript_targets}}{{end}}
    return # build
`,
		wscript.Build,
	)
	handle_err(err)

	_, err = fmt.Fprintf(
		r.w,
		"\n## EOF ##\n",
	)
	handle_err(err)

	return err
}

func w_tmpl(w *os.File, text string, data interface{}) error {
	t := template.New("wscript")
	t.Funcs(template.FuncMap{
		"trim": strings.TrimSpace,
		"as_pylist": func(alist interface{}) string {
			rv := reflect.ValueOf(alist)
			str := make([]string, 0, rv.Len())
			for i := 0; i < rv.Len(); i++ {
				s := rv.Index(i)
				str = append(str, fmt.Sprintf("%q", s))
			}
			return "[" + strings.Join(str, ", ") + "]"
		},
		"gen_wscript_pkg_deps": gen_wscript_pkg_deps,
		"gen_wscript_stmts":    gen_wscript_stmts,
		"gen_wscript_targets":  gen_wscript_targets,
	})
	template.Must(t.Parse(text))
	return t.Execute(w, data)
}

func w_gen_taglist(tags string) []string {
	str := make([]string, 0, strings.Count(tags, "&"))
	for _, v := range strings.Split(tags, "&") {
		v = strings.Trim(v, " ")
		if len(v) > 0 {
			str = append(str, v)
		}
	}
	return str
}

func w_py_strlist(str []string) string {
	o := make([]string, 0, len(str))
	for _, v := range str {
		vv, err := strconv.Unquote(v)
		if err != nil {
			vv = v
		}
		if strings.HasPrefix(vv, `"`) && strings.HasSuffix(vv, `"`) {
			if len(vv) > 1 {
				vv = vv[1 : len(vv)-1]
			}
		}
		o = append(o, fmt.Sprintf("%q", vv))
	}
	return strings.Join(o, ", ")
}

func w_gen_valdict_switch_str(indent string, values [][2]string) string {
	o := make([]string, 0, len(values))
	o = append(o, "(")
	for _, v := range values {
		tags := w_gen_taglist(v[0])
		key_fmt := "(%s)"
		if strings.Count(v[0], "&") <= 0 {
			key_fmt = "%s"
		}
		val_fmt := "%s"
		if strings.Count(v[1], ",") > 0 {
			val_fmt = "[%s]"
		}
		if len(v[1]) == 0 {
			val_fmt = "%q"
		}

		o = append(o,
			fmt.Sprintf(
				"%s  {%s: %s},",
				indent,
				fmt.Sprintf(key_fmt, w_py_strlist(tags)),
				fmt.Sprintf(val_fmt, v[1]),
			),
		)
	}
	o = append(o, indent+")")
	return strings.Join(o, "\n")
}

func w_py_hlib_value(indent string, fctname string, x hlib.Value) []string {
	str := make([]string, 0)

	values := make([][2]string, 0, len(x.Set))
	for _, v := range x.Set {
		k := v.Tag
		values = append(values, [2]string{k, w_py_strlist(v.Value)})
	}
	str = append(
		str,
		fmt.Sprintf(
			"ctx.%s(%q, %s)",
			fctname,
			x.Name,
			w_gen_valdict_switch_str(indent, values),
		),
	)

	return str
}

func gen_wscript_pkg_deps(pkg hlib.Package_t) string {
	const indent = "    "
	var str []string
	public_deps := make([]hlib.Dep_t, 0, len(pkg.Deps))
	private_deps := make([]hlib.Dep_t, 0, len(pkg.Deps))
	runtime_deps := make([]hlib.Dep_t, 0, len(pkg.Deps))
	for _, dep := range pkg.Deps {
		if dep.Type.HasMask(hlib.RuntimeDep) {
			runtime_deps = append(runtime_deps, dep)
		}
		if dep.Type.HasMask(hlib.PublicDep) {
			public_deps = append(public_deps, dep)
		}
		if dep.Type.HasMask(hlib.PrivateDep) {
			private_deps = append(private_deps, dep)
		}
	}

	str = append(str, "")
	if len(public_deps) > 0 {
		str = append(str, "## public dependencies")
		for _, dep := range public_deps {
			str = append(
				str,
				fmt.Sprintf(
					"ctx.use_pkg(%q, version=%q, public=True)",
					dep.Name,
					dep.Version,
				),
			)
		}
		str = append(str, "")
	} else {
		str = append(str, "## no public dependencies")
	}

	if len(private_deps) > 0 {
		str = append(str, "## private dependencies")
		for _, dep := range private_deps {
			str = append(
				str,
				fmt.Sprintf(
					"ctx.use_pkg(%q, version=%q, private=True)",
					dep.Name,
					dep.Version,
				),
			)
		}
		str = append(str, "")
	} else {
		str = append(str, "## no private dependencies")
	}

	if len(runtime_deps) > 0 {
		str = append(str, "## runtime dependencies")
		for _, dep := range runtime_deps {
			str = append(
				str,
				fmt.Sprintf(
					"ctx.use_pkg(%q, version=%q, runtime=True)",
					dep.Name,
					dep.Version,
				),
			)
		}
	} else {
		str = append(str, "## no public dependencies")
	}

	// reindent:
	for i, s := range str[1:] {
		str[i+1] = indent + s
	}

	return strings.Join(str, "\n")
}

func gen_wscript_stmts(stmt hlib.Stmt) string {
	const indent = "    "
	var str []string
	switch x := stmt.(type) {
	case *hlib.MacroStmt:
		str = []string{fmt.Sprintf("## macro %v", stmt)}
		str = append(
			str,
			w_py_hlib_value(indent, "hwaf_declare_macro", x.Value)...,
		)

	case *hlib.MacroAppendStmt:
		str = []string{fmt.Sprintf("## macro_append %v", stmt)}
		str = append(
			str,
			w_py_hlib_value(indent, "hwaf_macro_append", x.Value)...,
		)

	case *hlib.MacroPrependStmt:
		str = []string{fmt.Sprintf("## macro_prepend %v", stmt)}
		str = append(
			str,
			w_py_hlib_value(indent, "hwaf_macro_prepend", x.Value)...,
		)

	case *hlib.MacroRemoveStmt:
		str = []string{fmt.Sprintf("## macro_remove %v", stmt)}
		str = append(
			str,
			w_py_hlib_value(indent, "hwaf_macro_remove", x.Value)...,
		)

	case *hlib.TagStmt:
		str = []string{fmt.Sprintf("## tag %v", stmt)}
		values := w_py_strlist(x.Content)
		str = append(str,
			"ctx.hwaf_declare_tag(",
			fmt.Sprintf("%s%q,", indent, x.Name),
			fmt.Sprintf("%scontent=[%s]", indent, values),
			")",
		)

	case *hlib.PathStmt:
		str = []string{fmt.Sprintf("## path %v", stmt)}
		str = append(
			str,
			w_py_hlib_value(indent, "hwaf_declare_path", x.Value)...,
		)

	case *hlib.PathAppendStmt:
		str = []string{fmt.Sprintf("## path_append %v", stmt)}
		str = append(
			str,
			w_py_hlib_value(indent, "hwaf_path_append", x.Value)...,
		)

	case *hlib.PathPrependStmt:
		str = []string{fmt.Sprintf("## path_prepend %v", stmt)}
		str = append(
			str,
			w_py_hlib_value(indent, "hwaf_path_prepend", x.Value)...,
		)

	case *hlib.PathRemoveStmt:
		str = []string{fmt.Sprintf("## path_remove %v", stmt)}
		str = append(
			str,
			w_py_hlib_value(indent, "hwaf_path_remove", x.Value)...,
		)

	//case *hlib.ApplyPatternStmt:

	default:
		str = []string{fmt.Sprintf("### **** statement %T (%v)", stmt, stmt)}
	}

	// reindent:
	for i, s := range str[1:] {
		str[i+1] = indent + s
	}

	return strings.Join(str, "\n")
}

func gen_wscript_targets(tgts hlib.Targets_t) string {
	const indent = "    "
	var str []string

	cnv_values := func(values []hlib.Value) []string {
		out := make([]string, 0, len(values))
		for _, v := range values {
			// FIXME what about the non-default values ??
			out = append(out, v.Set[0].Value...)
		}
		return out
	}

	for i, tgt := range tgts {
		if i != 0 {
			str = append(str, "")
		}
		srcs := cnv_values(tgt.Source)
		str = append(str,
			"ctx(",
			fmt.Sprintf("%sfeatures = %q,", indent, tgt.Features),
			fmt.Sprintf("%sname     = %q,", indent, tgt.Name),
			fmt.Sprintf("%ssource   = [%s],", indent, w_py_strlist(srcs)),
		)

		for _, vv := range []struct {
			hdr    string
			values []hlib.Value
		}{
			{"use", tgt.Use},
			{"defines", tgt.Defines},
			{"cflags", tgt.CFlags},
			{"cxxflags", tgt.CxxFlags},
			{"linkflags", tgt.LinkFlags},
			{"shlibflags", tgt.ShlibFlags},
			{"stlibflags", tgt.StlibFlags},
			{"rpath", tgt.RPath},
			{"includes", tgt.Includes},
			{"export_includes", tgt.ExportIncludes},
		} {
			if len(vv.values) > 0 {
				vals := cnv_values(vv.values)
				str = append(str,
					fmt.Sprintf(
						"%s%s = [%s],",
						indent,
						vv.hdr,
						w_py_strlist(vals),
					),
				)
			}
		}
		str = append(str,
			")",
		)

	}

	// reindent:
	for i, s := range str[1:] {
		str[i+1] = indent + s
	}

	return strings.Join(str, "\n")
}

// EOF
